ClassLength:
  Max: 128

HashSyntax:
  Enabled: false

MethodLength:
  Max: 15

LineLength:
  Max: 160

SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space

SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

EmptyLinesAroundBody:
  Enabled: false

SignalException:
  Enabled: false

DoubleNegation:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '{}'

SingleSpaceBeforeFirstArg:
  Enabled: false

FileName:
  Exclude:
    - SUSEConnect

ClassAndModuleChildren:
  Enabled: false

GlobalVars:
  AllowedVariables: []

AllCops:
  Exclude:
    - kitchen/cookbooks/**/*
    - kitchen/tmp/**/*
    - vendor/**
