source 'https://rubygems.org'

# Provisioning
gem 'vagrant', github: 'mitchellh/vagrant', tag: 'v1.6.3'

group :development do
  gem 'librarian-chef'
end

group :plugins do
  gem 'vagrant-librarian-chef'
  gem 'vagrant-openstack-plugin'
end

group :test do
  gem 'chefspec'
  gem 'rspec'
  gem 'strainer'
end

