source 'https://rubygems.org'

gem 'vagrant'
gem 'rake'

group :development do
  gem 'berkshelf'
  gem 'knife-solo'
end

group :test do
  gem 'chefspec'
  gem 'rspec'
  gem 'strainer'
  gem 'debugger'
end
