source 'https://rubygems.org'

group :development do
  gem 'librarian-chef'
end

group :plugins do
  gem 'vagrant-librarian-chef'
  gem 'vagrant-openstack-plugin'
end

group :test do
  gem 'chefspec'
  gem 'rspec'
  gem 'strainer'
  gem 'debugger'
end

