$LOAD_PATH << 'lib'

require 'cloud_vm'

namespace :cloud do
  namespace :vm do
    desc 'Creates and starts new VM instance on cloud.suse.de; Optional parameter: name'
    task :create, :name do |_t, args|
      name = args.to_hash.key?(:name) ? args[:name] : 'SUSEConnect_testing'
      Cloud::VM.create(name)
    end

    desc 'Terminate VM instance on cloud.suse.de; Optional parameter: name'
    task :terminate, :name do |_t, args|
      name = args.to_hash.key?(:name) ? args[:name] : 'SUSEConnect_testing'
      Cloud::VM.destroy(name)
    end

    desc 'Deregister VM instance'
    task :deregister do |_t|
      Cloud::VM.deregister!
    end
  end
end

namespace :dotoscrc do
  desc 'Creates ~/.oscrc configuration file'
  task :create, [:username, :password] do |_t, args|
    args = args.to_hash
    if args.key?(:username) && args.key?(:password)
      username = args[:username]
      password = args[:password]

      oscrc = File.open(File.join(ENV['HOME'], '.oscrc'), 'w')
      oscrc.puts '[general]'
      oscrc.puts '[https://api.suse.de]'
      oscrc.puts "user=#{username}"
      oscrc.puts "pass=#{password}"
      oscrc.puts 'trusted_prj=SLE_12 SUSE:SLE-12:GA'
      oscrc.close
    else
      puts 'ERROR: Missing required parameters [:username, :password]'
    end
  end
end
