$LOAD_PATH << 'lib'

require 'cloud_vm'

namespace :cloud do
  namespace :vm do
    desc 'Creates and starts new VM instance on cloud.suse.de; Optional parameter: name'
    task :create, :name do |t, args|
      name = args.to_hash.key?(:name) ? args[:name] : 'SUSEConnect_testing'
      Cloud::VM.create(name)
    end

    desc 'Terminate VM instance on cloud.suse.de; Optional parameter: name'
    task :terminate, :name do |t, args|
      name = args.to_hash.key?(:name) ? args[:name] : 'SUSEConnect_testing'
      Cloud::VM.destroy(name)
    end

    desc 'Deregister VM instance'
    task :deregister do |t|
      Cloud::VM.deregister!
    end
  end
end
