$LOAD_PATH << 'lib'

require 'cloud_vm'
require 'debugger'

namespace :cloud do
  namespace :vm do
    desc 'Creates and starts new VM instance on cloud.suse.de; Optional parameter: name'
    task :create, :name do |t, args|
      args.to_hash.key?(:name) ? Cloud::VM.create(args[:name]) : Cloud::VM.create
    end

    desc 'Terminate VM instance on cloud.suse.de; Required parameter: name'
    task :terminate, :name do |t, args|
      if args.to_hash.key? :name
        Cloud::VM.destroy(args[:name])
      else
        puts 'Please specify the name of the virtual machine'
      end
    end
  end
end
