#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '..', 'lib')
require 'suse/connect/cli'

abort 'Root privileges are required to register products and change software repositories' unless Process.uid == 0
cli = SUSE::Connect::Cli.new(ARGV.dup)

begin
  cli.execute!
rescue => e
  puts "SUSEConnect error: #{e.class}: #{e.message}"
  cli.log.debug e.backtrace.join("\n")
end
